# Solving Linear Systems: 3 variables

In this notebook we will:
1. Use `NumPy` linear algebra package to find the solutions to the system of linear equations
2. Perform row reduction to bring matrix into row echelon form
3. Find the solution for the system of linear equations using row reduced matrix
4. Evaluate the determinant of the matrix
5. See the connection between matrix singularity and the number of solutions of the linear system

### import package

In [1]:
import numpy as np

## 1. Using NumPy linear algebra package to find the solutions to the system of linear equations

<a name='1.1'></a>
### 1.1 - System of Linear Equations

Here is a **system of linear equations** (or **linear system**) with three equations and three unknown variables:


$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

**To solve** this system of linear equations means to find such values of the variables $x_1$, $x_2$, $x_3$, that all of its equations are simultaneously satisfied.

In [2]:
A = np.array([
    [4,-3,1],
    [2,1,3],
    [-1,2,-5]], 
    dtype=np.dtype(float))
print(A)
print(A.shape)

[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]
(3, 3)


In [3]:
b = np.array([-10,0,17],dtype=np.dtype(float))
print(b)
print(b.shape)

[-10.   0.  17.]
(3,)


### Using Numpy's inbuilt `np.linalg.solve(A,b)` function

In [4]:
np.linalg.solve(A,b)

array([ 1.,  4., -2.])

### Finding the determinant using numpy's inbuilt `np.linalg.det(A)` function

In [5]:
A_det = np.linalg.det(A)
print("The determinant is: {:.2f}".format(A_det))

The determinant is: -60.00


## 2. Solving System of Linear Equations using Row Reduction¶

### 2.1 Preparation for Row Reduction - Stacking to a large Matrix

In [6]:
main = np.hstack((A,(b.reshape(3,1))))
main

array([[  4.,  -3.,   1., -10.],
       [  2.,   1.,   3.,   0.],
       [ -1.,   2.,  -5.,  17.]])

### 2.1 Defining Functions for Elementary Operations

### Function 1 - Multiplying Rows by a non-zero number

In [7]:
def Multiply_Rows(matrix, row_x, multiple):
    m_copy = matrix.copy()
    m_copy[row_x] = m_copy[row_x] * multiple
    return m_copy

### Function 2 - Multiplying and Adding Rows

In [8]:
def Add_Rows(matrix, row_x, row_y, multiple):
    m_copy = matrix.copy()
    m_copy[row_x] = (multiple * m_copy[row_y]) + m_copy[row_x]
    return m_copy

### Function 3 - Swaping Rows

In [9]:
def Swap_Rows(matrix, row_x, row_y):
    m_copy = matrix.copy()
    m_copy[[row_x, row_y]] = m_copy[[row_y,row_x]]
    return m_copy

In [10]:
main

array([[  4.,  -3.,   1., -10.],
       [  2.,   1.,   3.,   0.],
       [ -1.,   2.,  -5.,  17.]])

### 2.2 Calling the Functions

In [11]:
# Swapping 
A_ref = Swap_Rows(main,0,2)
A_ref

array([[ -1.,   2.,  -5.,  17.],
       [  2.,   1.,   3.,   0.],
       [  4.,  -3.,   1., -10.]])

Make the first elements in the second and third row zero

In [12]:
# multiply row 0 of the new matrix A_ref by 2 and add it to the row 1
A_ref = Add_Rows(A_ref, 1, 0, 2)
A_ref

array([[ -1.,   2.,  -5.,  17.],
       [  0.,   5.,  -7.,  34.],
       [  4.,  -3.,   1., -10.]])

In [13]:
# multiply row 0 of the new matrix A_ref by 4 and add it to the row 2
A_ref = Add_Rows(A_ref, 2, 0, 4)
A_ref

array([[ -1.,   2.,  -5.,  17.],
       [  0.,   5.,  -7.,  34.],
       [  0.,   5., -19.,  58.]])

The next step will be to perform an operation by putting the second element in the third row equal to zero:

In [14]:
A_ref = Add_Rows(A_ref, 2, 1, -1)
A_ref

array([[ -1.,   2.,  -5.,  17.],
       [  0.,   5.,  -7.,  34.],
       [  0.,   0., -12.,  24.]])

It is easy now to find the value of $x_3$ from the third row, as it corresponds to the equation $-12x_3=24$. Let's divide the row by -12:

In [15]:
A_ref = Multiply_Rows(A_ref, 2, -1/12)
A_ref

array([[-1.,  2., -5., 17.],
       [ 0.,  5., -7., 34.],
       [-0., -0.,  1., -2.]])

Now the second row of the matrix corresponds to the equation $5x_2-7x_3=34$ and the first row to the equation $-x_1+2x_2-5x_3=17$. Referring to the elements of the matrix, you can find the values of $x_2$ and $x_1$:

In [16]:
x_3 = -2

In [17]:
x_2 = (A_ref[1,3] - A_ref[1,2]*x_3)/A_ref[1,1]
x_2

4.0

In [18]:
x_1 = (A_ref[0,3]- (A_ref[0,1]*x_2) - (A_ref[0,2]*x_3))/A_ref[0,0]
x_1

1.0

In [19]:
print(x_1)
print(x_2)
print(x_3)

1.0
4.0
-2


### BONUS  - System of Linear Equations with No Solutions

Given another system of linear equations:

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=0, \end{cases}\tag{2}$$

let's find the determinant of the corresponding matrix.

In [20]:
A_2= np.array([
        [1, 1, 1],
        [0, 1, -3],
        [2, 1, 5]
    ], dtype=np.dtype(float))
A_2

array([[ 1.,  1.,  1.],
       [ 0.,  1., -3.],
       [ 2.,  1.,  5.]])

In [21]:
b_2 = np.array([2, 1, 0], dtype=np.dtype(float))
b_2

array([2., 1., 0.])

In [22]:
d_2 = np.linalg.det(A_2)
print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


In [23]:
try:
    np.linalg.solve(A_2,b_2)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix


In [24]:
main_2 = np.hstack((A_2, b_2.reshape((3, 1))))
main_2

array([[ 1.,  1.,  1.,  2.],
       [ 0.,  1., -3.,  1.],
       [ 2.,  1.,  5.,  0.]])

In [25]:
# multiply row 0 by -2 and add it to the row 2
A_ref2 = Add_Rows(main_2, 2, 0, -2)
A_ref2

array([[ 1.,  1.,  1.,  2.],
       [ 0.,  1., -3.,  1.],
       [ 0., -1.,  3., -4.]])

In [26]:
# add row 1 of the new matrix A_2_ref to the row 2
A_ref2 = Add_Rows(A_ref2, 2, 1, 1)
A_ref2

array([[ 1.,  1.,  1.,  2.],
       [ 0.,  1., -3.,  1.],
       [ 0.,  0.,  0., -3.]])

The last row will correspond to the equation $0=-3$ which has no solution. Thus the whole linear system $(2)$ has no solution.

### Bonus 2 - System of Linear Equations with Infinite Number of Solutions

You can bring system $(2)$ to consistency by changing only the free coefficients:

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=3. \end{cases}\tag{3}$$

Define the new array of free coefficients:

In [27]:
b_3 = np.array([2, 1, 3])
b_3

array([2, 1, 3])

In [28]:
main_3 = np.hstack((A_2, b_3.reshape((3, 1))))
main_3

array([[ 1.,  1.,  1.,  2.],
       [ 0.,  1., -3.,  1.],
       [ 2.,  1.,  5.,  3.]])

In [29]:
# multiply row 0 of the new matrix A_3_system by -2 and add it to the row 2
A_ref3 = Add_Rows(main_3, 2, 0, -2)
A_ref3

array([[ 1.,  1.,  1.,  2.],
       [ 0.,  1., -3.,  1.],
       [ 0., -1.,  3., -1.]])

In [30]:
# add row 1 of the new matrix A_3_ref to the row 2
A_ref3 = Add_Rows(A_ref3, 2, 1, 1)
A_ref3

array([[ 1.,  1.,  1.,  2.],
       [ 0.,  1., -3.,  1.],
       [ 0.,  0.,  0.,  0.]])

Thus from the corresponding linear system

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 0=0, \end{cases}\tag{4}$$

you can find that $x_2=1+3x_3$, substitute it into the first equation and find $x_1$. Thus the solutions of the linear system $(3)$ are:

$$\begin{cases} 
x_1=1-4x_3, \\ x_2=1+3x_3, \end{cases}\tag{5}$$

where $x_3$ is any real number.

The End! <br>
We used the `NumPy` functions to solve a system of equations and implemented it  solving it manually. As expected, using a predefined function is much easier, but gives much less insight into what is happening under the hood. 
<br>Remember that `np.linalg.solve` gives an error if there are no or infinitely many solutions, thus when implementing it you will have to think carefully so not to make your program crash.